### ISSUE TITLE
JIT PLUGIN AND FS

### ISSUE THREAD

**Issue by RoderickHarty** [edgyaf/samp-ac-black-diamond#1] opened 2024-08-01 07:28 UTC
Hello,
I would like to report an issue with FS loading and JIT PLUGIN.

When the JIT PLUGIN is used, the AC Black Diamond FS doesn't load, and this freezes the server starting process.

I attach the last line printed in log:

[07:42:25] ---------------
[07:42:25]   Loading filterscript 'android.amx'...
[07:42:25]   Loading filterscript 'AC_Black_Diamond.amx'...

How can I resolve this issue? Is there a FS version that doesn't have this problem?

Thank You.

**Comment by edgyaf** [comment] 2024-08-05 20:48
Thanks for reporting, the issue is fixed in the v2.0.3 release. Please reopen the issue if it still persists.

**Closed as completed by edgyaf** 2024-08-05 20:48 UTC
